lang: en
url: 'https://bestthaifruits.com' # the base hostname & protocol for your site, e.g. http://example.com

collections:
  fruits:
    output: true
    permalink: /:slug
  pages:
    output: true
    permalink: /:slug
    sort_by: position

partners:
  ews.ru:
  x5.ru:
  vprok.ru:
  lavka.yandex:
  eda.yandex:
    link: 'https://eda.yandex/lavka/?category=15984521ecc0421293343f0f90f14843000100010001&isGrocery=true'
  tvoydom.ru:
  vkusvill.ru:
    link: 'https://vkusvill.ru/goods/vkusvillays/ovoshchi_frukty_yagody_griby_zamorozhennye/'
  icevkusvill.ru:
  globalfoods.ru:
    link: 'http://globalfoods.ru/catalog/?q=bestthaifruits'
  delikateska.ru:
  freshfrost.ru:
  standart-mitino.ru:

defaults:
  #languages
  - scope:
      path: ''
    values:
      lang: en
      layout: default
  - scope:
      path: ru
    values:
      lang: ru

t:
  en:
    title: Best Thai Fruits
    unavailable: Temporary<br>Unavailable
    description: >-
      Premium Ripe Thai Fruits: Mini-Pineapple Phulae, Mango Nam Dok Mai and Avocado.
      Individual Quick Freezing and Delivery Around the World
    download: Download
    layout:
      title: Premium Thai Fruits
      subtitle: Individual Quick Freezing and Delivery Around the World
    nutrition:
      info: Nutrition Facts per 100g
      calories: Calories
      fat: Fat
      protein: Protein
      carbs: Carbohydrate
      g: g
      kcal: kCal
    package:
      info: Package and Shipping
    company:
      line_before:
      before:
      title: Best Thai Fruit
      after: Co. Ltd.
      address: 53/36 Moo 2, Vichit, Muang, Phuket, Thailand 83000
      email: info@bestthaifruits.com
      phone1: +668-0707-3842
      # phone1: +7-964-931-3480
      whatsapp: 79649313480
      line: bestthaifruits
  ru:
    title: Лучшие Тайские Фрукты
    unavailable: Временно недоступно
    description: >-
      Премиальные Cпелые Тайские Фрукты: Мини-Анансы Пуле, Манго Нам Док Май и Авокадо. Индивидуальная шоковая
      заморозка и доставка по всему миру
    download: Скачать
    layout:
      title: Спелые Тайские Фрукты
      subtitle: Индивидуальная шоковая заморозка и доставка по всему миру
    nutrition:
      info: Пищевая ценность в 100г
      calories: Калорийность
      fat: Жир
      protein: Белок
      carbs: Углеводы
      g: г
      kcal: ккал
    package:
      info: Упаковка и загрузка
    company:
      line_before: Представитель в России
      before: ООО
      title: Бест Тай Фрут Рус
      after:
      address: ИНН&nbsp;7734433970 ОГРН&nbsp;1207700133475
      email: ru@bestthaifruits.com
      phone1: +7-906-705-80-57
      phone2:
      whatsapp: 79067058057
      line:
