lang: en
url: "https://bestthaifruits.com" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  fruits:
    output: true
    permalink: /:slug

defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: ru
    values:
      lang: ru

t:
  en:
    title: Best Thai Fruits
    description: >-
      Premium Ripe Thai Fruits: Mini-Pineapple Phulae, Mango Nam Dok Mai and Avocado.
      Individual Quick Freezing and Delivery Around the World
    layout:
      title: Premium Thai Fruits
      subtitle: Individual Quick Freezing and Delivery Around the World
    nutrition:
      info: Nutrition Facts for 100g
      calories: Calories
      fat: Fat
      protein: Protein
      carbs: Carbohydrate
      g: g
      kcal: kCal
  ru:
    title: Лучшие Тайские Фрукты
    description: >-
      Премиальные Cпелые Тайские Фрукты: Мини-Анансы Пуле, Манго Нам Док Май и Авокадо. Индивидуальная шоковая
      заморозка и доставка по всему миру
    layout:
      title: Спелые Тайские Фрукты
      subtitle: Индивидуальная шоковая заморозка и доставка по всему миру
    nutrition:
      info: Пищевая ценность в 100г
      calories: Калорийность
      fat: Жир
      protein: Белок
      carbs: Углеводы
      g: г
      kcal: ккал
